import os

BOT_SALT=os.getenv("BOT_SALT")
BOT_AWS_SERVER_PUBLIC_KEY=os.getenv("BOT_AWS_SERVER_PUBLIC_KEY")
BOT_AWS_SERVER_SECRET_KEY=os.getenv("BOT_AWS_SERVER_SECRET_KEY")
AUTH0_MGMT_API_CLIENT_ID=os.getenv("AUTH0_MGMT_API_CLIENT_ID")
AUTH0_MGMT_API_SECRET=os.getenv("AUTH0_MGMT_API_SECRET")