import os

BOT_SALT=os.environ.get("BOT_SALT")
BOT_AWS_SERVER_PUBLIC_KEY=os.environ.get("BOT_AWS_SERVER_PUBLIC_KEY")
BOT_AWS_SERVER_SECRET_KEY=os.environ.get("BOT_AWS_SERVER_SECRET_KEY")
AUTH0_MGMT_API_CLIENT_ID=os.environ.get("AUTH0_MGMT_API_CLIENT_ID")
AUTH0_MGMT_API_SECRET=os.environ.get("AUTH0_MGMT_API_SECRET")